### PR TITLE
Support browsers from before 2020

### PR DESCRIPTION
**Pull request by L3P3**
This change follows https://github.com/cdr/code-server/pull/4579

### CODE REVIEW

**Comment by jsjoeio** [comment]
We'll need to test this to make sure everything works still.

## Steps to Test
1. checkout branch locally with `gh pr checkout 23`
2. [Follow docs](https://coder.com/docs/code-server/latest/CONTRIBUTING#development-workflow) for linking `vscode` repo locally
3. [Follow docs](https://coder.com/docs/code-server/latest/CONTRIBUTING#build) to create a build
4. Test build locally

**Comment by jsjoeio** [comment]
Hmm...I'm seeing a bunch of type errors. @L3P3 could you test this locally and let me know if you're seeing the same? We might not be able to do this 🤔 (or it might require more work).
```javascript
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts(86,29): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts(1226,24): Type 'HTMLCollection' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts(1242,21): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/testing/test/browser/testObjectTree.ts(57,22): Type 'NodeListOf<HTMLElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/test/browser/ui/tree/objectTree.test.ts(223,19): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/browser/parts/views/treeView.ts(1334,27): Type 'DataTransferItemList' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/browser/parts/views/treeView.ts(1338,28): Parameter 'dataValue' implicitly has an 'any' type.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts(1570,24): Type 'HTMLCollection' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/files/browser/fileImportExport.ts(113,22): Type 'FileList' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/splitview/paneview.ts(587,14): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/dialog/dialog.ts(120,21): Type 'NodeListOf<HTMLAnchorElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/dialog/dialog.ts(255,26): Type 'NodeListOf<HTMLAnchorElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/dialog/dialog.ts(437,22): Type 'HTMLCollectionOf<HTMLAnchorElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/platform/contextkey/browser/contextKeyService.ts(429,69): Property 'values' does not exist on type 'DOMTokenList'. Did you mean 'value'?
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/editor/contrib/hover/modesContentHover.ts(346,75): Property 'values' does not exist on type 'DOMTokenList'. Did you mean 'value'?
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/editor/contrib/colorPicker/colorContributions.ts(40,74): Property 'values' does not exist on type 'DOMTokenList'. Did you mean 'value'?
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/markdownRenderer.ts(275,21): Type 'HTMLCollectionOf<HTMLImageElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Finished compilation with 17 errors after 206935 ms
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts(86,29): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts(1226,24): Type 'HTMLCollection' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts(1242,21): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/testing/test/browser/testObjectTree.ts(57,22): Type 'NodeListOf<HTMLElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/test/browser/ui/tree/objectTree.test.ts(223,19): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/browser/parts/views/treeView.ts(1334,27): Type 'DataTransferItemList' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/browser/parts/views/treeView.ts(1338,28): Parameter 'dataValue' implicitly has an 'any' type.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts(1570,24): Type 'HTMLCollection' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/workbench/contrib/files/browser/fileImportExport.ts(113,22): Type 'FileList' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/splitview/paneview.ts(587,14): Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/dialog/dialog.ts(120,21): Type 'NodeListOf<HTMLAnchorElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/dialog/dialog.ts(255,26): Type 'NodeListOf<HTMLAnchorElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/ui/dialog/dialog.ts(437,22): Type 'HTMLCollectionOf<HTMLAnchorElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/platform/contextkey/browser/contextKeyService.ts(429,69): Property 'values' does not exist on type 'DOMTokenList'. Did you mean 'value'?
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/editor/contrib/hover/modesContentHover.ts(346,75): Property 'values' does not exist on type 'DOMTokenList'. Did you mean 'value'?
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/editor/contrib/colorPicker/colorContributions.ts(40,74): Property 'values' does not exist on type 'DOMTokenList'. Did you mean 'value'?
[15:29:44] Error: /Users/jp/Dev/coder/vscode/src/vs/base/browser/markdownRenderer.ts(275,21): Type 'HTMLCollectionOf<HTMLImageElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
```

I think we'll hold off on this until after 4.0.0 is released

**Comment by jsjoeio** [comment]
@code-asher tested this yesterday and didn't see these same errors. What are you seeing @L3P3? I see you modified the `lib`. Think that fixed this?

**Comment by code-asher** [comment]
Weirdly I did start seeing the iterator errors the next day so I am not sure what happened :shrug:  `dom.iterable` does seem like it should fix it.  We ought to add a build step to the CI here.

**Comment by L3P3** [comment]
Can it be merged now? The mentioned errors were resolved with the "lib" setting...

**Review by code-asher — APPROVED** [review]
Thank you for the ping!

**Pull request merged**
